# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gui.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setWindowModality(QtCore.Qt.WindowModal)
        MainWindow.resize(1134, 726)
        MainWindow.setMinimumSize(QtCore.QSize(800, 600))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.centralwidget.setMinimumSize(QtCore.QSize(800, 600))
        self.centralwidget.setAutoFillBackground(True)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setContentsMargins(3, 3, 3, 3)
        self.verticalLayout.setSpacing(3)
        self.verticalLayout.setObjectName("verticalLayout")
        self.verticalLayoutThe = QtWidgets.QVBoxLayout()
        self.verticalLayoutThe.setSpacing(3)
        self.verticalLayoutThe.setObjectName("verticalLayoutThe")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.BxPlotPlaceholder = QtWidgets.QWidget(self.centralwidget)
        self.BxPlotPlaceholder.setMinimumSize(QtCore.QSize(0, 300))
        self.BxPlotPlaceholder.setObjectName("BxPlotPlaceholder")
        self.horizontalLayout.addWidget(self.BxPlotPlaceholder)
        self.groupBoxControls = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBoxControls.setMinimumSize(QtCore.QSize(300, 0))
        self.groupBoxControls.setMaximumSize(QtCore.QSize(300, 16777215))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.groupBoxControls.setFont(font)
        self.groupBoxControls.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.groupBoxControls.setCheckable(False)
        self.groupBoxControls.setObjectName("groupBoxControls")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.groupBoxControls)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(9, 39, 281, 261))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout_GroupBoxControls = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout_GroupBoxControls.setSizeConstraint(QtWidgets.QLayout.SetNoConstraint)
        self.verticalLayout_GroupBoxControls.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_GroupBoxControls.setSpacing(0)
        self.verticalLayout_GroupBoxControls.setObjectName("verticalLayout_GroupBoxControls")
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_GroupBoxControls.addItem(spacerItem)
        self.pauseButton = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.pauseButton.setCheckable(True)
        self.pauseButton.setDefault(True)
        self.pauseButton.setFlat(False)
        self.pauseButton.setObjectName("pauseButton")
        self.verticalLayout_GroupBoxControls.addWidget(self.pauseButton)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_GroupBoxControls.addItem(spacerItem1)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_GroupBoxControls.addItem(spacerItem2)
        self.SaveVisibleButton = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.SaveVisibleButton.setObjectName("SaveVisibleButton")
        self.verticalLayout_GroupBoxControls.addWidget(self.SaveVisibleButton)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_GroupBoxControls.addItem(spacerItem3)
        self.saveButton = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.saveButton.setCheckable(True)
        self.saveButton.setObjectName("saveButton")
        self.verticalLayout_GroupBoxControls.addWidget(self.saveButton)
        spacerItem4 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_GroupBoxControls.addItem(spacerItem4)
        spacerItem5 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_GroupBoxControls.addItem(spacerItem5)
        self.label = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label.setObjectName("label")
        self.verticalLayout_GroupBoxControls.addWidget(self.label)
        self.spinBox = QtWidgets.QSpinBox(self.verticalLayoutWidget)
        self.spinBox.setMinimumSize(QtCore.QSize(70, 0))
        self.spinBox.setMaximumSize(QtCore.QSize(90, 16777215))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.spinBox.setFont(font)
        self.spinBox.setMinimum(1)
        self.spinBox.setMaximum(100)
        self.spinBox.setProperty("value", 10)
        self.spinBox.setObjectName("spinBox")
        self.verticalLayout_GroupBoxControls.addWidget(self.spinBox)
        spacerItem6 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_GroupBoxControls.addItem(spacerItem6)
        self.verticalLayout_GroupBoxControls.setStretch(1, 1)
        self.verticalLayout_GroupBoxControls.setStretch(3, 1)
        self.verticalLayout_GroupBoxControls.setStretch(4, 1)
        self.verticalLayout_GroupBoxControls.setStretch(8, 1)
        self.horizontalLayout.addWidget(self.groupBoxControls)
        self.verticalLayoutThe.addLayout(self.horizontalLayout)
        self.dataLabel = QtWidgets.QLabel(self.centralwidget)
        self.dataLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.dataLabel.setObjectName("dataLabel")
        self.verticalLayoutThe.addWidget(self.dataLabel)
        self.dataGridLayout = QtWidgets.QGridLayout()
        self.dataGridLayout.setSizeConstraint(QtWidgets.QLayout.SetFixedSize)
        self.dataGridLayout.setContentsMargins(5, 5, 5, 5)
        self.dataGridLayout.setObjectName("dataGridLayout")
        self.label_9 = QtWidgets.QLabel(self.centralwidget)
        self.label_9.setMaximumSize(QtCore.QSize(50, 16777215))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.dataGridLayout.addWidget(self.label_9, 1, 5, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setMaximumSize(QtCore.QSize(50, 16777215))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.dataGridLayout.addWidget(self.label_2, 1, 2, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setMaximumSize(QtCore.QSize(70, 16777215))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.label_3.setFont(font)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.dataGridLayout.addWidget(self.label_3, 2, 0, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(18)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.dataGridLayout.addWidget(self.label_6, 3, 2, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(18)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.dataGridLayout.addWidget(self.label_5, 2, 2, 1, 1)
        self.BxLabel = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(18)
        self.BxLabel.setFont(font)
        self.BxLabel.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.BxLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.BxLabel.setObjectName("BxLabel")
        self.dataGridLayout.addWidget(self.BxLabel, 1, 1, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setMaximumSize(QtCore.QSize(70, 16777215))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.label_4.setFont(font)
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.dataGridLayout.addWidget(self.label_4, 3, 0, 1, 1)
        self.BzLabel = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(18)
        self.BzLabel.setFont(font)
        self.BzLabel.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.BzLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.BzLabel.setObjectName("BzLabel")
        self.dataGridLayout.addWidget(self.BzLabel, 3, 1, 1, 1)
        self.BtLabel = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(18)
        self.BtLabel.setFont(font)
        self.BtLabel.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.BtLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.BtLabel.setObjectName("BtLabel")
        self.dataGridLayout.addWidget(self.BtLabel, 1, 4, 1, 1)
        self.BxlabelE = QtWidgets.QLabel(self.centralwidget)
        self.BxlabelE.setMaximumSize(QtCore.QSize(70, 16777215))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.BxlabelE.setFont(font)
        self.BxlabelE.setAlignment(QtCore.Qt.AlignCenter)
        self.BxlabelE.setObjectName("BxlabelE")
        self.dataGridLayout.addWidget(self.BxlabelE, 1, 0, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(18)
        self.label_7.setFont(font)
        self.label_7.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_7.setObjectName("label_7")
        self.dataGridLayout.addWidget(self.label_7, 1, 3, 1, 1)
        self.PLabel = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(18)
        self.PLabel.setFont(font)
        self.PLabel.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.PLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.PLabel.setObjectName("PLabel")
        self.dataGridLayout.addWidget(self.PLabel, 3, 4, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(18)
        self.label_8.setFont(font)
        self.label_8.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_8.setObjectName("label_8")
        self.dataGridLayout.addWidget(self.label_8, 3, 3, 1, 1)
        self.label_10 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(18)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.dataGridLayout.addWidget(self.label_10, 3, 5, 1, 1)
        self.ByLabel = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(18)
        self.ByLabel.setFont(font)
        self.ByLabel.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.ByLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.ByLabel.setObjectName("ByLabel")
        self.dataGridLayout.addWidget(self.ByLabel, 2, 1, 1, 1)
        self.AplaceholderWidget = QtWidgets.QWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.AplaceholderWidget.sizePolicy().hasHeightForWidth())
        self.AplaceholderWidget.setSizePolicy(sizePolicy)
        self.AplaceholderWidget.setMinimumSize(QtCore.QSize(300, 300))
        self.AplaceholderWidget.setMaximumSize(QtCore.QSize(300, 300))
        self.AplaceholderWidget.setObjectName("AplaceholderWidget")
        self.dataGridLayout.addWidget(self.AplaceholderWidget, 1, 6, 3, 1)
        self.verticalLayoutThe.addLayout(self.dataGridLayout)
        self.verticalLayout.addLayout(self.verticalLayoutThe)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setEnabled(True)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1134, 26))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setEnabled(False)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionSome_function = QtWidgets.QAction(MainWindow)
        self.actionSome_function.setObjectName("actionSome_function")
        self.actionNice_option = QtWidgets.QAction(MainWindow)
        self.actionNice_option.setObjectName("actionNice_option")
        self.actionMore_options = QtWidgets.QAction(MainWindow)
        self.actionMore_options.setObjectName("actionMore_options")
        self.menuFile.addAction(self.actionSome_function)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionNice_option)
        self.menuFile.addAction(self.actionMore_options)
        self.menubar.addAction(self.menuFile.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "GMR Vector magnetometer"))
        self.groupBoxControls.setTitle(_translate("MainWindow", "Controls"))
        self.pauseButton.setText(_translate("MainWindow", "Pause"))
        self.SaveVisibleButton.setText(_translate("MainWindow", "Save visible data"))
        self.saveButton.setText(_translate("MainWindow", "Save untill stopped"))
        self.label.setText(_translate("MainWindow", "Usrednjavanje"))
        self.dataLabel.setText(_translate("MainWindow", "Raw averaged data"))
        self.label_9.setText(_translate("MainWindow", "nT"))
        self.label_2.setText(_translate("MainWindow", "nT"))
        self.label_3.setText(_translate("MainWindow", "By ="))
        self.label_6.setText(_translate("MainWindow", "nT"))
        self.label_5.setText(_translate("MainWindow", "nT"))
        self.BxLabel.setText(_translate("MainWindow", "Bx value"))
        self.label_4.setText(_translate("MainWindow", "Bz ="))
        self.BzLabel.setText(_translate("MainWindow", "Bz value"))
        self.BtLabel.setText(_translate("MainWindow", "|B| value"))
        self.BxlabelE.setText(_translate("MainWindow", "Bx ="))
        self.label_7.setText(_translate("MainWindow", "|B| ="))
        self.PLabel.setText(_translate("MainWindow", "P value"))
        self.label_8.setText(_translate("MainWindow", "P ="))
        self.label_10.setText(_translate("MainWindow", "mbar"))
        self.ByLabel.setText(_translate("MainWindow", "By value"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.actionSome_function.setText(_translate("MainWindow", "Some function"))
        self.actionNice_option.setText(_translate("MainWindow", "Nice option"))
        self.actionMore_options.setText(_translate("MainWindow", "More options"))

